feat: implemented sum
UNICT-Quality-Development/git-course-exercises pull request #109
Opened 2022-10-19 15:35 UTC by Picred

2022-10-19 16:00 UTC, Helias commented on exercises/sum.cpp
> +  return 0;
potresti sostituire 0 con
```c++
#define EXIT_SUCCESS 0
...
return EXIT_SUCCESS;
```

2022-10-19 16:06 UTC, IgnazioGul commented on exercises/sum.cpp
> +  return 0;
Meglio usare una macro per i valori handcoded (non una variabile perchè occupa memora, il simbolo di macro viene sostituito con il valore reale in fase di compilazione, per info: https://www.arduino.cc/reference/en/language/structure/further-syntax/define/):
```diff
+ #define EXIT_SUCCESS 0
+  return EXIT_SUCCESS;
- return 0;
```

2022-10-19 16:14 UTC, IgnazioGul requested changes

2022-10-19 16:14 UTC, IgnazioGul commented on exercises/sum.cpp
> +}
Meglio passare i pasaremtri per riferimento così da evitare una copia di due double superflua:
```diff
+ T sum(T& n1, T& n2){
- T sum (T n1, T n2){
```
NB: passare parametri per riferimento solo nelle funzioni che non alterano il valore dei parametri stessi. 
Nel nostro caso non c'è problema.

2022-10-20 08:48 UTC, Helias approved these changes

2022-10-28 06:07 UTC, closed without merging