Implemented sum.cpp
UNICT-Quality-Development/git-course-exercises pull request #117
Opened 2022-10-19 15:43 UTC by RobyMark

2022-10-19 16:25 UTC, IgnazioGul requested changes
Il codice in sé per sé va bene, ti chiederei comunque di attenzionare i seguenti punti (oltre a quelli segnalati sopra):
- Conventional commit: bisogna seguire le convenzioni sui commit message (https://www.conventionalcommits.org/en/v1.0.0/). Dai un'occhiata alla sezione "Why Use Conventional Commits" perchè spiega i reali motivi per il quale le grandi aziende IT seguono questa convenzione.
Per modificare il messaggio dei due commit che hai pushato dovresti fare un rebase (https://linuxize.com/post/change-git-commit-message/#changing-an-older-or-multiple-commits)

- Indentazione del codice: la cosa ottimale sarebbe installare un formatter per il linguaggio di riferimento che formatta il documento ad ogni salvataggio. 
Basta googlare in base all'IDE che stai utilizzando. Es: per VS code -> https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting

Per il resto tutto ok, ottimo lavoro :)

2022-10-19 16:25 UTC, IgnazioGul commented on exercises/sum.cpp
> +}
Manca il return 0;
Anche se il programma funziona comunque ritornare il valore 0 a fine esecuzione ti serve per assicurarti che se l'esecuzione termina proprio con valore 0 alloral'esecuzione ha terminato correttamente. 
Caso contrario (presenza di errori a runtime) si avrà un exit code diverso.
Meglio usare una macro per i valori handcoded , come lo 0 nel return.
 Questo perchè le macro create con #define non una variabile perchè occupa memora, il simbolo di macro viene sostituito con il valore reale in fase di compilazione, per info: https://www.arduino.cc/reference/en/language/structure/further-syntax/define/:
```diff
+ #define EXIT_SUCCESS 0
....
+ return EXIT_SUCCESS;
- return 0;
```

2022-10-19 16:25 UTC, IgnazioGul commented on exercises/sum.cpp
> +	cout<<"La somma e': "<<(a+b)<<"\n";
Le parentesi sono superflue

2022-10-20 08:48 UTC, Helias approved these changes

2023-10-17 16:58 UTC, closed without merging