chore: implemented a switch case
UNICT-Quality-Development/git-course-exercises pull request #119
Opened 2022-10-19 15:48 UTC by Davide496

2022-10-19 16:36 UTC, IgnazioGul requested changes

2022-10-19 16:36 UTC, IgnazioGul commented on exercises/ex1.cpp
>    return 0;
Meglio usare una macro per i valori handcoded (non una variabile perchè occupa memora, il simbolo di macro viene sostituito con il valore reale in fase di compilazione, per info: https://www.arduino.cc/reference/en/language/structure/further-syntax/define/):
```diff
+ #define EXIT_SUCCESS 0
....
+ return EXIT_SUCCESS;
- return 0;
```

2022-10-20 08:48 UTC, Helias commented on exercises/ex1.cpp
> +      cout << "\nInvalid input! Please enter week number between 1-7.\n";
non hai messo il cout << endl dopo lo switch case, comunque non è rilevante in realtà

2022-10-20 08:49 UTC, Helias approved these changes

2023-10-17 16:58 UTC, closed without merging